name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: # <-- Добавьте эту секцию
      contents: write # <-- Дает права на запись в репозиторий (коммиты, теги)
      pull-requests: write # <-- Может понадобиться для некоторых плагинов (опционально)
      id-token: write # <-- Для OIDC, если используете (опционально)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Необходим для полного анализа истории коммитов
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.10"
      - name: Install dependencies
        run: npm ci
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Токен для создания релизов GitHub
        run: npx semantic-release
